### ISSUE TITLE
calculateCheckDigit returns Err InvalidMod11Number

### ISSUE THREAD

**Issue by brodul** [Carlsson87/mod11#1]
@Carlsson87 

`calculateCheckDigit` returns` Err InvalidMod11Number`

For example `[6]` or `[1, 2, 3, 4, 5, 6, 7, 8, 9]`

Expected behavior would be to return `Ok 0`

**Comment by Carlsson87** [comment]
Hi. Thank you for reporting an issue.

From what I understand the modulus 11 algorithm can be implemented in different ways. And the examples you give in your description are actually invalid according to the description in the document I referenced in the readme ([this one](https://www.bankgirot.se/globalassets/dokument/anvandarmanualer/11-modul.pdf)). The very last sentence on the last page says:
> Note that if the product is equal to 1 and the check digit is 10, then the account
number cannot be used as a basis of a modulus 11 account number.

The implementation of modulus 11 that is used at https://planetcalc.com/7744/ would actually return an `X` as the check digit.

**Comment by brodul** [comment]
Tnx, for the quick reply. Funny thing the mod 11 algorithm.

Makes sense. Its really simple for me to wrap `calculateCheckDigit ` and return whatever is needed.

Tnx for the lib, helps a lot. 😄
